# changelog
# fixed a bug where dropping the brush while a different item was in your mainhand would cause that item to be deleted
# fixed a bug where scheduled events didn't work properly on modded servers with multiverse-mc
#
#

name: MC Paint
version: v1.8.0-beta1
output: build

data_pack:
  description: "Create custom paintings!\nBy Eroxen."
  min_format: [107, 1]
  max_format: 107
  zipped: true
  load:
    - src

resource_pack:
  zipped: true
  description: "Create custom paintings!\nBy Eroxen."
  min_format: [88, 0]
  max_format: 88
  load:
    - src

require:
  - bolt
  - eroxified2

pipeline:
  - mecha
  - beet.contrib.load

meta:
  load:
    data_pack:
      data: libs/*/data