name: MC Paint
version: v1.6.0-dev1
output: build

data_pack:
  load:
    - libs/bs.view-1.21.8-v3.1.0

resource_pack:
  pack_format: 64
  description: "Create custom paintings!\nBy Eroxen."
  supported_formats: [63, 64]
  load:
    - src

pipeline:
  - data_pack:
      pack_format: 81
      description: "Create custom paintings!\nBy Eroxen."
      supported_formats: [80, 81]
      load:
        - src
    require:
      - bolt
      - eroxified2
    pipeline:
      - mecha