name: MC Paint
version: v1.6.0
output: build

data_pack:
  pack_format: 81
  description: "Create custom paintings!\nBy Eroxen."
  supported_formats: [80, 81]
  zipped: true
  load:
    - src

resource_pack:
  zipped: true
  pack_format: 64
  description: "Create custom paintings!\nBy Eroxen."
  supported_formats: [63, 64]
  load:
    - src

require:
  - bolt
  - eroxified2

pipeline:
  - mecha
  - beet.contrib.load

meta:
  load:
    data_pack:
      data: libs/*/data